### ISSUE TITLE
1.15 is the same commit as 1.14 and is missing the 1.15 fixes

### ISSUE THREAD

**Issue by OrGoN3** [dragoninjector-project/DragonInjector-UpdateTool#3]
You attempted to release 1.15 but rereleased the same commit for 1.14. these lack the changes mentioned in the 1.15 changelog. It was clearly an accident. Please fix so we can use 1.15. thanks!

**Comment by jeromedontdev** [comment]
It's not the same commit. I'm unsure what you are missing but I just redownloaded and verified that it is in fact doing what the change I implemented does.

**Comment by OrGoN3** [comment]
I'm seeing them as identical 44a1297. That corresponds to remove needless writes, but bootloader flash and changing the version string to 1.15 come after. Maybe you just selected the wrong commit when making the release?

**Comment by jeromedontdev** [comment]
It's there:

https://github.com/dragoninjector-project/DragonInjector-UpdateTool/commit/1cb169821ea9f1fd41cae32fea59d74bb83f634b

**Comment by OrGoN3** [comment]
![Screenshot_20191122-101308](https://user-images.githubusercontent.com/56672656/69437183-cdb43a80-0d10-11ea-8474-d19ba2932d00.png)

**Comment by jeromedontdev** [comment]
It's just the order in which I did it. I pushed the release right before the commit. In the future I will be more conscience about it.
